adds scaffolding for sorting plugin
tillprochaska/edtrio pull request #1
Opened 2018-11-18 10:56 UTC by usame-algan

2018-11-18 17:03 UTC, tillprochaska requested changes
Vielleicht könnten wie die eigentliche Komponente schon mal in ihre eigene Datei `SortNode.jsx` auslagern. Dann haben wir da nicht den ganzen Boilerplate-Code drin.

2018-11-18 17:03 UTC, tillprochaska commented on .eslintrc
> +    "linebreak-style": [2, "windows"],
Hast du die Linter-Config absichtlich bearbeitet?

2018-11-18 17:03 UTC, tillprochaska commented on src/plugins/sort/index.js
> +function SortNode(props) {
Ich würde vermuten, dass diese Component doch etwas komplexer wird und ihren eigenen State braucht. Deshalb würde ich sie gleich als Klasse definieren und nicht den funktionellen Ansatz wählen.

```js
class SortNode extends React.component {
  ...
  render() {
    return <div {...props}>Sort</div>;
  }
  ...
}
```

2018-11-18 17:33 UTC, usame-algan commented on .eslintrc
> +    "linebreak-style": [2, "windows"],
Ja, habe haufenweise LF/CRLF Fehler erhalten. Können es ggf. auch erstmal rausnehmen mit

`"linebreak-style": 0`
https://stackoverflow.com/questions/39114446/how-can-i-write-a-eslint-rule-for-linebreak-style-changing-depending-on-windo

2018-11-18 19:57 UTC, adrianjost commented on .eslintrc
> +    "linebreak-style": [2, "windows"],
Wir nutzen bei der Schul-Cloud immer Unix Style. Für den Linter gibt es nen fix, welcher schon im schulcloud-client repo ist. Kann ich morgen Mal einfügen. Liegt daran, dass GitHub beim Checkout alles zu den lokalen Linebreaks umwandelt und beim Checkout wieder zu Unix.

2018-11-21 10:39 UTC, adrianjost commented
Folgende Datei einfach im Root Ordner einbauen sollte das LF Problem fixen. Hab leider gerade keine Zeit das selbst einzubauen

`.gitattributes`
```
#git on windows will convert lf to crlf which makes eslint freak out. This keeps it in linux style.
*.js text eol=lf
```

2018-11-22 11:06 UTC, tillprochaska approved these changes

2018-11-22 11:13 UTC, merged