Feature/sort basic ui
tillprochaska/edtrio pull request #3
Opened 2018-12-07 20:14 UTC by adrianjost

After hours of frustration where I haven't coded a single line, I've decided to copy the prototype from the other edtrio-team and changed it step by step to meet our requirements. A couple hours later now the result can be seen on the screenshots below.
Sadly I had to throw away our old code structure. Feel free to refactor everything here. I haven't had time for this.

# Features
 - Table based UI to write down the question term and the appropriate solution
 - UI can switch to "student-mode"
   - A student can click on the card to flip between the question term and the solution
   - can go to the next question with a separate button
   - can reset the view state to redo all cards.

# Screenshots
![image](https://user-images.githubusercontent.com/22987140/49670257-597f7900-fa64-11e8-8010-6b2ba108cf85.png)
![image](https://user-images.githubusercontent.com/22987140/49670268-6308e100-fa64-11e8-95bd-d968825625a2.png)
![image](https://user-images.githubusercontent.com/22987140/49670362-c5fa7800-fa64-11e8-836c-98ffacb7a9cb.png)

2018-12-10 10:33 UTC, tillprochaska commented
I’ll have a closer look into this later today/this evening. Didn’t manage to review earlier, sorry!

2018-12-11 20:21 UTC, usame-algan commented on src/plugins/sorting-task/index.tsx
> +  const newQuestion = Block.create({
Should this be `newSolution`?

2018-12-11 20:21 UTC, usame-algan commented on src/plugins/sorting-task/index.tsx
> +      newQuestion,
Same as above

2018-12-11 20:21 UTC, usame-algan commented on src/plugins/sorting-task/index.tsx
> +  const newAnswer = Block.create({
`newQuestion`?

2018-12-11 21:50 UTC, tillprochaska requested changes
Thanks for bootstrapping the basic elements! 💯I haven’t understood everything, but this is probably because I’ve not understood all the Slate-specific concepts. However, I’ve added some minor suggestions/comments, but these just details. :)

Also, the current code throws some errors. In the cases I’ve been able to find the cause for them, I’ve added a comment at the relevant lines.

2018-12-11 21:50 UTC, tillprochaska commented on src/plugins/plus-menu/PlusMenu.tsx
> +  onClickSortButton,
I'd try to be consistent with naimg things. As the plugin is now called `sorting-task`, I think we should name that function `onClickSortingTaskButton`.

```suggestion
  onClickSortingTaskButton,
```

2018-12-11 21:50 UTC, tillprochaska commented on src/plugins/plus-menu/PlusMenu.tsx
> +          onClickSortButton,
```suggestion
          onClickSortingTaskButton,
```

2018-12-11 21:50 UTC, tillprochaska commented on src/plugins/sorting-task/styles.css
> +.question-card{
```suggestion
.question-card {
```

2018-12-11 21:50 UTC, tillprochaska commented on src/plugins/sorting-task/styles.css
> +.question-card:after{
```suggestion
.question-card::after {
```

`:after` (with a single colon) has been used in the past. However, in order to distinguish between pseudo-selectors and actual pseudo-elements, a double colon should be used for the latter.

2018-12-11 21:50 UTC, tillprochaska commented on src/plugins/sorting-task/index.tsx
> +        <table {...attributes}>
Directly nesting `tr`s inside of a `table` element throws an error. While I think the HTML specs do not require wrapping `thead`, `tbody` elements etc., React doesn’t seem to like it.

```html
<thead>
  <tr>
    <th>Begriff</th>
    <th>Musterlösung</th>
  </tr>
</thead>
<tbody>
  {children}
</tbody>
```

2018-12-11 21:50 UTC, tillprochaska commented on src/plugins/plus-menu/actions.ts
> +export const onClickSortButton = (event: any, editor: Editor) => {
```suggestion
export const onClickSortingTaskButton = (event: any, editor: Editor) => {
```

2018-12-11 21:53 UTC, tillprochaska commented
In the following, I’ve written down some general thoughts on another possible approach to this task. But that shouldn’t stop us from merging this PR! 👍 

I’m not sure if we should rely that much on Slate.js for the sorting task itself. Building a vanilla React component that doesn’t rely on Slate-specific concepts (like blocks etc.) might make things much easier. Here are some of the reasons:

Slate is great for »freeform content«. That’s why it’s a good choice for the editor and the document itself. On the other hand, the UI for our sorting task component are known upfront and their structure is more or less fixed. For example, when entering the terms, there should always be two inputs – one for the term and one for the explanation. Using Slate to build this interface will introduce some problems. For example, currently the user is able to delete these two inputs by simply pressing the backspace key. Also, it's currently possible to add code blocks in those cells.

We could probably work around all these issues. But there’s a solutions that’s way more straight-forward. Using basic inputs etc. to compose the interface might just be enough. 

We might even build the interface completely as a stand-alone component and integrate it with the editor at the end of our process. This way, we would not directly depend on the `edtr.io` project or Slate which might be a big advantage as the SC team seems to have some major refactorings (which in turn might result in breaking changes) in the pipeline.

Hopefully that was understandable…?!

2018-12-13 14:10 UTC, tom2022 approved these changes
As just agreed, approval from my side, let's merge and proceed with the current status.

2018-12-13 16:42 UTC, merged